title: Michael LaCovara # your name (or website title) here
logo: "/images/IMG_2831.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A graduate of St. John's University with a Masters Degree in Applied and Computational Mathematics. Possesses a wide range of experience in data anaylsis, including data preprocessing, advanced statistical methods, and machine learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/michael-lacovara/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
